#+Author: joshp1
#+Discription: A story about a young girl that finds otu she can control people with her mind also hear their thoughts. This is the story of how she got her powers and how it develops

* TeleLoli
** Chapter 1
   Sitting on the floor of a garage is a young eight year old girl. She's dribbeling a basket ball and shooting hoops in side. Her dad owns a large three car garage. That after her mom caught her talking to a Skinny man that most likely
 was a drifter trying to get her into the van then saw her daughter lift up her skirt. The man had a bundle of cash he was handing her. Her mom yelled at him then called the cops. Krystal acted like she didn't know what wsa going on. Her mom
 drug her back in. 

In side her mom huged her and asked, "Did he touch you?" Krystal shook her head. Her mom nods and says, "Good. Now did he give you anything" Krystal shook her head again. 

Her mom nods and says, "The police will be hear in a minute go to your room" Krystal nods.

She's sitting on the floor playing with her barbies whe she hears a soft knock on her door. Then a cop wearing all blue walks in. He smiles and says, "I just have a couple questions" She nods and says, "Ok sir" He smiles and says, "Your mom
told me you lifted your skirt for him did he threaten you?" She shook her head and said, "Let me see up your skirt and I'll give you two hundred dollars. But mom stopped me before he could give it to me". 

THe cop nods and says, "So he brabed you? Did he take any pictures?" Krystal replies, "No he said he wanted to but I said that'd b another two hundred" The cop replies, "Next time when a stranger asks you something like that run away and 
tell your mom or dad ok?" She nods and says, "OK sir"

She goes back to playing with dolls. She walks the man doll up to barbie and says, "Hey hot stuff what does it take to get you in my truck?" She thren replies, "About three hundred, then anotehr grand for sex and five hundred for a blow 
job." She talks for theman again, "Nice lets go".

She walks them over t a car when she hears a bing from her laptop. SHe gets happy and opens is. On it is a message from a man named, Timii, "Hey Cutiigirl what happened?" She replies, "Sorry Tim mom caught me. I said we should do that somewhere
else. Now mom's called the cops" He replies shit then disconnects. She unfriends him then goes back to her barbies.

She has barbie's face against the man's crotch whith his pants down saying, "Oh slut this is nice. I think I'm going to cum" She has barbie look up and sasy, "Not yet big stuff. I want your big cock in me" she undressed barbie and puts hir 
on top and starts sliding hir on him making moaning sounds. until she talked for the male and says, "Oh God Here it comes" Barbie gets off oand says, "no NO no"

She puts barbies face against the crotch again and mimics a blow job then says, "ho here it comes again. I can't stop. Oh god yes" 

She makes barbie whipe off her face adn says, "Your the best. She then dresses them and puts barbie back in her spot"

She hears her mom yell. So she runs to the kitchen.

Her mom has a smile on her face and says, "I just wanted to tell you. You can stop worring they got the perv that was bothering you" Krystal giggles and says, "OK. Thank you" Then goes back to her room mumbeling, "He was one of my best
clients. I didn't even get to see his dick yet though. At least I've made a grand off of him" 

She sits down in front of her laptop and gets on. She sees she has six messages. the first three is people saying 'Hey' to her she says, "I'll talk to them later. I need money now" She opnes one that says, "Hey sweet cheeks" She smiles 
and sees it's from a user name hotspot321. She replies, "Hey daddy" He replies, "Sorry buddy not into that today. I'm going to be a actual dad" Krystal sincs down and says, "Damn. Like Jimmy872 going all good on me" But sees, "What will
it take for a pussy shot? Huh honey?" She smiles and says, "OK" she cracks her knuckles and replies,"two hundred" She hears a ping and a money symbol pop up in her icon tray. She clicks it and sees two hundred then below for goods"

She takes off her panties then possitions the camera so he can see. She lifts up her skirt and he post, "Oh fuck yeah" She moves teh camera up and says, "OK want more?" He posts, "Damn I almost cummed" She gigles and says, "Sorry you know
the rules. You get ten seconds" He replies, "I know I know" She post, "But I'll give you a show you a nip if I can see a dick" He posts, "LOL you expect me to pay to see you but you want it free?" She groans and syas, "Every time" Before 
typing, "Showing you my nipple ain't enough" He repies, "Sorry honey but puberty ain't called yet. But I will if you play with your self while I jack off" She posts, "That's another two hundred" He disconnects and she says, "DAMN IT!" She 
hears another ping and sees two thousand deposited. She blinks and says, "Damn" Then she hears a bing and sees, "Sorry about that. THere two grand. Want to fuck?" HEr hands starts shaking and post, "I'm a virgin" He replies, "Yeah yeah
you can play that" She replies, "Really I've never done it" He replies, "Damn you really stick to the cute girl act don't you?" She sighs and says, "Sir I've never fucked a guy, My mom puts a filter on my computer so this chat is the only
way I get to see stuff. So please. Ok here. I'll play with myself naked. If you show me" He replies, "Show me your cherry" "What's that?" He repiles, "Damn you really do" She sees a picture pop up of a girls' pussy with a hyman" then 
that's a cherry .

She turns around and possistions her self so she is pointing to the camera then spreads her pussy apart. Counts to ten then sits back down. He posts, "Damn your a whore with a cherry damn. How has no one fucked your hot ass yet"

She replies, "Uncle Jonny was going to but mom caught him before I could get in the car" He replies, "LOL, That amature. A sweet slut lik eyou usaually cost more so fuck yeah" She blinks and says, "More" then post I'm sending your money 
back I just don't fil right" He replies, "Oh shit no plaese. I'll apy you more. here" There's a ping and she sees, three thousand. She smiles and types, "OK I guess I will. Lets meet behind the old store. The abanoned one at eleven I can't
sneak out earlier" He rpiees, "I think I just got hustled by a eight year old whore but fuck I want that cherry" She giggles tehn types, "See you then. Bye" she closes her laptop and goes to get a shower.
