** Chapter 2 
She crawls into her bed in her pajamas. her mom walks in and kisses hre forhead and says, "OK buddy. Goodnight. 
Remember me and dad have a meeting tomarow so we'll be gone befroe you get up at 8 ok?" She smiles and says, "OK mommy
I'll be a good little angle" Her mom smiles and says, "Great see yo utomarow night" 

She gets up and locks her door and says, "And you'll be going straight to bed tnoight. She waits till she hears her 
paretns door shut then gets on her phone and sees it's nine" she smiles and says, "Great"

She waits another hour before geting out of bed taking off her pajamas and putting on her pink skirt that she's
known to always wear and a white shirt with a blue cat that again is her signature look. She don't bother with putting
underwear on because for five grand he's going to get his money worth.

She opens her window and climbs out it. Before runing around back then threw a patch off woods behind her house. Only
stopping once to look back adn chck if her parents lights are on.

Befroe long she's behind the abandoned store waiting. when a old black pickup ford. He pulls infront of her and says, 
"Hey" She waves and says, "Hey daddy" He laughs and says, "That's ok. But for now can you call me Uncle Benny?" She
shakes her head and syas, "I have a actual uncle Benny" He replies, "But you have a actual daddy don't you?" She 
nods and says, "But I cal him dad. So calling you daddy ain't the same. Anyway, Daddy is second Uncle is first"

He nods and says, "I know but uncle Jonny is in jail now and probably not going to b out for a while" 
She groans and syas, "Ok we'll talk about this on the chat but right now your on the clock" In raelity she has no idea
what time it is she's just copying what she's seen on movies her sister showed her, and what her sister taught her.
She's frustrated that her sister never showed her porn but said." If your still a virign when your sixteen I'll 
introduce you. But right now you can bring in teh big bucks being inocent".

He opens his passanger side door. Her heart is racing as she walks over and opnes the door. after climbing in she sees
him with a tile drapped over him.  She sits down and says, "OK I really" He puts the truck in gear and drives off. 
she's scared and syas, "What are you doing?" He replies, "Don't worry your safe with daddy. I'm taking you to a safe
place. How much time do I got?" She looks at the clock on his truck and sees eleven thirty and says, "Two hours or 
until you cum" He nods and says, "Great".

They arrive to the location which is  down a dirt road. He smiels and says, "I just want to  be safe but are you
sure?" Krystal nods. He smiles and says, "Ok then lift up your skirt" She does and he takes off the towel. She
gets wide eyed when she sees his dick that to her looks huge. 

"Why is it sticking out like that?", she asks him, curiously. He smiles and says, "Because I"m excited now get naked"
She's shaking a little from fear but does. 

He reaches and touches her chest and says, "Come here" She does and he pushes  her head dwon and says, "open your 
mouth and when my dick goes in suck" SHe smells it and is nervous, "Why does it smell weird?" he just continues slowly
pushing her head down until it goes into her mouth. 

It taste salty but she begins sucking. He is paying for this. SHe feels her pull at her hair then say< "do this" then
pushes her back in. Until she feels it hit the back of her throut and thinks she's going to throw up. But after a 
couple of times. 

He lays back and relaxes. He sighs and reaches between her legs and starts tickeling her pussy. he pulls his dick
out of her mouth and says, "Daddy that's good" He keeps on and says, "Keep blowing me " She don't knwo what it is but
assumes it's what she's been doing. so she does. 

She begins feeling excited and a tickle inside that makes her want to ggigle. So her breathing picks up. But again he 
grabs her hair and pulls his dick out of her mouth. 

She holds her head and says, "Damn could you please not pull my hair daddy?" He replies, " lay down and spread your legs
whore. She takes a deap breath and does. 

He looks down and smiles seeing her tight pussy. He strokes his wet dick before positioning himself between her legs and
insirts his cock into her and begins thrusting. 

At first she felt a sting but after it wasn't so bad. She reaches up and says, "Can I touch you?" He replies, "I'd slap
you if you didn't whore" Sh reaches up and feels his hard chest and lets out a maon. He looks down and asks, "Like that
don't you slut?" She nods. She's begining to feel that tickeling feeling from earlier again but stronger. She feels her
pussy stretching with his cock being shove way up into her. It hurt for a bit but the more she gets into it the better it
feels.

His breathing picks up she's confused but says, "Does daddy like it?" He moans oh yes fuck me slut" He goes back stroking his dick and says, '
"ride me whore" HE gets on him and he says, "Put my cokc in your pussy" She does then he thrust up then downa dn says, "Go up and down doing
that to my cock" she does and loves the feeling of control she has. SHe quckly feels the butterflies feeling up her stomach
again before he groans hard then she something warm feeling her. She looks down at him and says, "Your into pee?" He looks
down and says, "That's not pee whore" She finaly says, "Ok you cumed can you take me home? And quit calling me whore?
He sslaps her and says, "I paid you five grand I'll call you wahat ever I liked now get cdresssed. 

After she does he says, "Now get out" She opens the door and climbs out. then loks back and says, "This is going ot cost you alredy 
got what the one time. He says, "No for telling me what to do walk home fucking whore" He reaches and slams the door and leaves.

She watches his tail lights fade away crying before realising she does need to get home. But has no idea where to go. 
So she goes in the same direction he went.

A hour passes and she ends up being in at ehte old store. As she passses by the store she hears something inside.

"FUCK YOU SAID YOU'LL HAVE SOMEOEN. NOW WHAT?"

she hten hears a second, "Please boss he was here"

"WELL GO FIND HIM" 

She starts to run but hears, "Hey girl" she takes off runing before she fels a hand on her shoulder and then is being drug bacwokrds.

She's screaming for help but he puts a hand on her mouth and rushes her inside.

A fat man with a eard says, "FUCK IT. THAT'S NOT HIM IDIOT!"

She's crying and says, "please don't yell"

The fat man walks up and says, "oh pore baby she's crying"

He slaps her hard causing her to be fall on the floor. He leans down and says, "WHo are you"? She is to busy crying. The
other walks up and says, "Boss she heard everyting. But since the he's not hear can't we use her?" The fat man loks down
and says, "A body is a body"

The smaller man lifts up her skirt. Krystal screams but the otehr holds her down while the other lifts up her skirt again and says, "
Boss she's not wearing panties and she's aful bloody I think we should call teh cops she was raped" The fat man replies, "She's going
to be dead in minute probably so shut up"

The other does and sticks the needle into her leg. 

Krystal feels a burning goign up her leg then all over her body. She lets out a scream becasue the burning

The small man asks, "So boss what now?" The fat man replies, "She didn't die. So I guess we need to kill her and put this shit on the street"
the small man replies, "But she ain't high" The fat man whispers, "That don't matter we sell a bunch for six hundred a shot we're rich and move
on. SO kill her.

The skinny man nods then pull out a gun. Krystal screams, "NO don't " The skiny man stands there pointing the gun. THe fan man hits him and 
says, "Shoot dumb ass" The skinny man relpies, "I can't" The fat man shakes his head and says, "Let me" he takes the gun and again Krystal 
screams , "no Don't please don't" the fat man is just standin thtere and yells, "Damn it what's wrong ith this thing?" 

The skinny man shakes his head and says, "i'l take care of her" He pulls out a knife and walks to her. She screams, "NO stab your boss if you
going to stab anyone". He laughs but then turns and goes for his boss. 

His boss yells, "THE FUCK?" but next their wrestling on the floor before she hears a loud bang and blood spraoys over the floor. The boss looks
at her and says "The fuck is you?" KRystal crying says, "Are. Its. What the fuck are you" the man shakes his head and syas, "your correcting
a man that's going to shoot you?" Krystal crulls up and says, "Shoot yourself"

She hears a bang then, "Why the fuck did I do that" Krystal panicking says, "in the face shoot yourself in the face" then right in front of her
he's panicking as he puts the gun between his eyes. he's actually crying and says, "What the fuck"

She's runs out o fth ebuilding screaming after the bang 
