* Chapter 3
Krystal is on her bed shaking. SHe did manage to put her pajamas on but sleep didn't come. Now her mom walks in and says, "Wake up honey" Krystal who's been crying all night says, "Go away mom" Next she hears the door shut. She looks
and sees her mom gone. She walks into the kitchen. Her dad looks and says, "What happened" SHe respons, "Leave me alone" her dad turns aroudn and starts talking to her mom.

Krystal gets a bowl of ceriel befroe going back to her room. to get dressed. She then remembers the night beofre and decides to chck her chat and sees. A message from another but not from the one she called her daddy. But then she sees
him come online so ehs messages, "Daddy why did you dropm eoff?' he replies, "Shut up whore". She cries and says, "Please I need someoen to talk to" He post, "huh now send me some picture sof you pussy whore" She can't take anymore and
says, "your not my daddy bye" she unfriends him then. She sighs and says, "Two in two days. Glad I have a hundred more" she then turns on her web came after taking off ehr school shirt and puting her signature one on. and says, "Hello.
guys something bad happensed tonight" As soon as she started braodcasting lots came on especting a tease but instead she's crying and says, "please I need to talk" 

One pops up and says, "I can talk but it ain't free" She replies, "WHy?" His responce is, "When have you ever gave up a free peek?" She sighs and lifts up her shirt and says, "There free peek" He response, "Nice flat chest. But I want
to see of a peek of downstairs" She tells him, "I'm sorry I lost my virginity to daddy last night. So I don't think you want to see that" He responce ,"HEll yeah your still blood?' 

She's saved by her mom. Who 2says, "Ok come on Krystal time for school" Krystal responds, "one sec" her mom a second later says, "Ok come on"  Krystal says, "Mom that wasn't a second" Hse hears, "Yes it was now go to school" Krystal grabs her
backpack and heads to cshool.

At school a girl walks up and says, "Hey cumstal" Krystal rolls her eys and syas, "Oh fuck yourself Kelly" Kelly pulls her pants downa nd begins fingering herself. Krystal blink sadn says, "The hell?" Kelly is crying from embarresemnt 
"I don't know why I did this" some boys are yelling and other girls are laughing. Then she hears, "Kelly Anne pul her pants up" Followed by , "Sorry Mrs Sanders but I can't" Krystal looks and says, "Stop Kelly", Defending the teacher.

Kelly suddenly stops. The teacher says, "Krystal you need to get to class" Krystal smiles and says, "You need to get to class and forget this happende" hEr teacher turns and walks away. She then yells, OK everyone ignore us and forget
this happened.  Go on with your own business" Kelly is leaving but Krystal says, "Stop" Kelly stops, Krystal smiles and says, "You love meking me hit mysefl so pucnh yoursefl in theface. Kelly does it. Krystal says, "Keep on until you 
pass out" 

Kelly begins punching herself in the face and Krystal goes to class. THe rest of school she has fun with her new foun power. Then at the end of the day. She walks up to a boy in a grade above her and says, "Jimy I want to see your dick"
He frowns and says, "Go to hell"Krystal says, "SHow me your dick and jack off" She pulls out her phone as he puls down his pants and begisn jacking off.
